name: qrapp
description: "Quick Response to Quick Stream."
publish_to: 'none'
version: 1.2.0+2

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^7.1.4
  package_info_plus: ^9.0.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  web_socket_channel: ^3.0.3
  device_info_plus: ^12.3.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
